### ISSUE TITLE
Default for innodb_page_size is 16k, docs mention it is 4k

### ISSUE THREAD

**Issue by mdcallag** [NetApp/SQL_Storage_Benchmark#1]
See the MySQL docs [for innodb_page_size](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_page_size)

The [SSB readme](https://github.com/NetApp/SQL_Storage_Benchmark/blob/main/README.md) states it is 4k. The default is 16k.
```
Currently the default page size for MySQL is 4KB and SSB currently only has support for 16KB page size, although this will likely change in future versions.
```

**Comment by rodrigonascimento** [comment]
Hi Mark,

Thanks for pointing that out. I fixed our documentation.
